### ISSUE TITLE
Clicking on posts in Disqus section does not go to posts

### ISSUE THREAD

**Issue by SpaceShot** [jchadwick/StaticVoidPodcastWebsite#1]
Example... the typescript podcast links to: https://www.staticvoidpodcast.com/?p=1251

This ends up going to the home page... not the linked page.

_Update_ Maybe only for the typescript show

**Comment by jchadwick** [comment]
Thanks for the feedback.  We will look into this.

**Comment by SpaceShot** [comment]
wont fix wtf!!

**Comment by jchadwick** [comment]
Cannot reproduce.  Please provide specific steps

**Comment by SpaceShot** [comment]
1) hear of static void podcast (difficult, rare to repro)
2) Go to staticvoidpodcast.com site
3) listen to show
4) decide the show is worth listening to
5) look for older shows
6) exhaust list of shows on main page
7) notice that Typescript show post is in the Disqus section
8) click on link
9) end up back on home page
10) wonder if typescript exists

**Comment by jchadwick** [comment]
Oh, ok.  I see it now.

**Comment by jchadwick** [comment]
This is an issue with some of the Disqus links linking to the old Wordpress URLs.  Updated in Disqus and the change should be propagating soon.
